title: KorQuAD
author: Panoramedia
email: panoramedia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Korean Question Answering Dataset

twitter_username: macrod68
github_username:  macrod68

sass:
    style: compressed